# Model setup
LAC.sample_rate: 40000
LAC.encoder_dim: 32
LAC.encoder_rates: [2, 4, 8, 8,]
LAC.decoder_dim: 512
LAC.decoder_rates: [8, 8, 4, 2]

# Quantization
LAC.n_codebooks: 4
LAC.codebook_size: 1024
LAC.codebook_dim: 12
LAC.quantizer_dropout: false

# Discriminator
Discriminator.sample_rate: 40000
Discriminator.rates: []
Discriminator.periods: [ 3, 5, 7]
Discriminator.fft_sizes: [2048, 1024, 512]
Discriminator.bands:
  - [0.0, 0.1]
  - [0.1, 0.25]
  - [0.25, 0.5]
  - [0.5, 0.75]
  - [0.75, 1.0]

# Optimization
AutoClip.frequency: 1
AutoClip.percentile: 10

AdamW.betas: [0.8, 0.99]
discriminator/AdamW.lr: 0.0001
discriminator/ExponentialLR.gamma: 0.999996
generator/AdamW.lr: 0.0001
generator/ExponentialLR.gamma: 0.999996

amp: false
val_batch_size: 7
device: cuda
epoch_length: 1000
num_epochs: 3000
save_epochs: [10, 50, 100, 250, 500]
num_workers: 8
save_audio_epochs: 10
val_idx: [0, 1, 2, 3, 4, 5, 6, 7]
seed: 0
lambdas:
  mel/loss: 15.0
  adv/feat_loss: 2.0
  adv/gen_loss: 1.0
  vq/commitment_loss: 0.25
  vq/codebook_loss: 1.0

VolumeNorm.db: [const, -16]

# Transforms
build_transform.preprocess:
  - Identity
build_transform.augment_prob: 0.95
build_transform.augment:
  - LowPass
  - HighPass
  - Equalizer
  - FrequencyMask
  # - CorruptPhase
  - BackgroundNoise
  # - FrequencyNoise
  - ClippingDistortion
  - RoomImpulseResponse
build_transform.postprocess:
  - VolumeNorm
  - RescaleAudio
  - ShiftPhase

RoomImpulseResponse.prob: 0.9

BackgroundNoise.prob: 0.8
BackgroundNoise.snr: ["uniform", 10, 30]
BackgroundNoise.sources: 
- /media/CHONK/patrick/data/noise-database


HighPass.prob: 0.3
HighPass.cutoff: ["choice", [100, 200, 400, 800]]

LowPass.prob: 0.4
LowPass.cutoff: ["choice", [8000, 1200, 2400, 4800, 9600, 16000]]

ClippingDistortion.prob: 0.3

Equalizer.prob: 0.7
Equalizer.eq_amt: ["uniform", -3, 3]

FrequencyMask.prob: 0.5
# FrequencyNoise.prob: 0.5

CorruptPhase.prob: 0.3

RoomImpulseResponse.sources: 
- /media/CHONK/patrick/data/MIT-IR
- /media/CHONK/patrick/data/rir-database


# Loss setup
MultiScaleSTFTLoss.window_lengths: [2048, 512]
MelSpectrogramLoss.n_mels: [5, 10, 20, 40, 80, 160, 320]
MelSpectrogramLoss.window_lengths: [32, 64, 128, 256, 512, 1024, 2048]
MelSpectrogramLoss.mel_fmin: [0, 0, 0, 0, 0, 0, 0]
MelSpectrogramLoss.mel_fmax: [null, null, null, null, null, null, null]
MelSpectrogramLoss.pow: 1.0
MelSpectrogramLoss.clamp_eps: 1.0e-5
MelSpectrogramLoss.mag_weight: 0.0

# Data
batch_size: 7
train/AudioDataset.duration: 0.75
train/AudioDataset.n_examples: 10000000

val/AudioDataset.duration: 5.0
val/build_transform.augment_prob: 1.0
val/AudioDataset.n_examples: 250

AudioLoader.shuffle: true
AudioDataset.without_replacement: true

train/build_dataset.folders:
  music:
    - /media/CHONK/data/nsynth/nsynth-train/audio

val/build_dataset.folders:
  music:
    - /media/CHONK/data/nsynth/nsynth-valid/audio